# Generated by Django 4.2.6 on 2023-10-29 14:48

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Gallery",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("textField", models.CharField(max_length=255)),
                ("fileInput1", models.ImageField(upload_to="pictures/")),
                ("fileInput2", models.ImageField(upload_to="pictures/")),
                (
                    "integerInput",
                    models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4)]),
                ),
            ],
        ),
    ]
