# Generated by Django 4.2.6 on 2023-10-30 14:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pages", "0002_alter_gallery_fileinput1_alter_gallery_fileinput2"),
    ]

    operations = [
        migrations.CreateModel(
            name="QuestionGallery",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "question_text",
                    models.CharField(
                        help_text="Enter the question name here",
                        max_length=255,
                        verbose_name="Question Text",
                    ),
                ),
                (
                    "question_file",
                    models.ImageField(
                        help_text="Upload the question file",
                        max_length=200,
                        upload_to="pictures/",
                        verbose_name="Question File",
                    ),
                ),
                (
                    "answer_file",
                    models.ImageField(
                        help_text="Upload the answer file",
                        max_length=200,
                        upload_to="pictures/",
                        verbose_name="Answer File",
                    ),
                ),
                (
                    "answer_integer",
                    models.IntegerField(
                        choices=[(1, 1), (2, 2), (3, 3), (4, 4)],
                        help_text="Choose an integer as the answer (1 to 4)",
                        verbose_name="Answer Integer",
                    ),
                ),
            ],
            options={
                "verbose_name": "Question Gallery",
                "verbose_name_plural": "Question Galleries",
            },
        ),
        migrations.DeleteModel(
            name="Gallery",
        ),
    ]
